const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    ADMIN_PROCESS_LOGOUT: 'ADMIN_PROCESS_LOGOUT',

    //customer
    CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
    CUSTOMER_LOGIN_FAIL: 'CUSTOMER_LOGIN_FAIL',
    CUSTOMER_PROCESS_LOGOUT: 'CUSTOMER_PROCESS_LOGOUT',

    //seller
    SELLER_LOGIN_SUCCESS: 'SELLER_LOGIN_SUCCESS',
    SELLER_LOGIN_FAIL: 'SELLER_LOGIN_FAIL',
    SELLER_PROCESS_LOGOUT: 'SELLER_PROCESS_LOGOUT',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
})

export default actionTypes;